export const constants = {

    GET_LATEST_SUCCESS:'GET_LATEST_SUCCESS',
    GET_LATEST_FAILURE:'GET_LATEST_FAILURE',
    GET_UPCOMING_SUCCESS:'GET_UPCOMING_SUCCESS',
    GET_UPCOMING_FAILURE:'GET_UPCOMING_FAILURE',
    GET_DETAILS_SUCCESS:'GET_DETAILS_SUCCESS',
    GET_DETAILS_FAILURE:'GET_DETAILS_FAILURE',
    GET_EVENTS_SUCCESS:'GET_EVENTS_SUCCESS',
    GET_EVENTS_FAILURE:'GET_EVENTS_FAILURE',
    SAVE_BOOKING_INFO:'SAVE_BOOKING_INFO',
    SAVE_USER_SELECTS:'SAVE_USER_SELECTS',
    SET_LATEST_MOVIES:'SET_LATEST_MOVIES',
    SET_UPCOMING_MOVIES:'SET_UPCOMING_MOVIES',
    SET_EVENTS:'SET_EVENTS'
    
};